CREATE DATABASE AUDIENCELAB_INTERNAL_PROD;
CREATE SCHEMA AUDIENCELAB_INTERNAL_PROD.RAW_DATA;


CREATE TRANSIENT DATABASE FOUR_EYES;
ALTER DATABASE FOUR_EYES
SET DATA_RETENTION_TIME_IN_DAYS=0;


CREATE TRANSIENT DATABASE STATISTICS;
ALTER DATABASE STATISTICS
SET DATA_RETENTION_TIME_IN_DAYS=0;


CREATE TRANSIENT DATABASE TROVO;
ALTER DATABASE TROVO
SET DATA_RETENTION_TIME_IN_DAYS=0;
CREATE TRANSIENT SCHEMA TROVO.RAW_DATA;
ALTER SCHEMA TROVO.RAW_DATA
SET DATA_RETENTION_TIME_IN_DAYS=0;
CREATE TRANSIENT SCHEMA TROVO.TEST;
ALTER SCHEMA TROVO.TEST
SET DATA_RETENTION_TIME_IN_DAYS=0;