USE ROLE SYSADMIN;

CREATE OR REPLACE USER AUDIENCEUSER;

CREATE OR REPLACE USER ENRICHMENTUSER;

CREATE OR REPLACE USER KEYWORDUSER;

CREATE OR REPLACE USER STAGINGPIXEL;

CREATE OR REPLACE USER LORENZO;

CREATE OR REPLACE USER YAPHOA001;

CREATE OR REPLACE USER STAT_USER;

-- 0.7) Create ROLES with access to objects:

CREATE OR REPLACE ROLE PIXEL_AGENT;

CREATE OR REPLACE ROLE STATISTICS_USER;

