GRANT ROLE PIXEL_AGENT TO USER STAGINGPIXEL;

GRANT ROLE PIXEL_AGENT TO USER AUDIENCEUSER;
GRANT ROLE PIXEL_AGENT TO USER ENRICHMENTUSER;
GRANT ROLE PIXEL_AGENT TO USER KEYWORDUSER;



GRANT ROLE STATISTICS_USER TO USER STAT_USER;