-- Seeing if simple command works
COPY INTO PIXEL_RESOLUTIONS.USER1."RESOLUTIONS_PIX_e0bfc1fc-8a06-48a8-b221-673653f0020e"
FROM
    (
          SELECT
          $1 IDENTITY_ID,
          $2 DATE,
          $3 HTTP_REFERER,
          $4 REQUEST_URI,
          REPLACE($5,'"','') AS ZIP,
          $6 EMAIL,
          $7 FIRSTNAME,
          $8 LASTNAME,
          $9 ADDRESS,
          $10 CITY,
          $11 STATE,
          REPLACE($12,'"','') AS ZIPCODE,
          REPLACE($13, '"', '') AS PLUS_4,
          $14 COUNTYNAME,
          $15 LATITUDE,
          $16 LONGITUDE,
          $17 MARITALSTATUS,
          $18 ESTIMATEDINCOMERANGE,
          $19 DATEOFBIRTH,
          $20 BIRTHYEAR,
          $21 AGE,
          $22 GENDER,
          $23 INFERREDCREDITSCORE,
          $24 ETHNIC,
          $25 DWELLINGTYPE,
          $26 HOMEOWNERRENTER,
          $27 HOMEVALUE,
          $28 AUTOVIN,
          $29 YEAR,
          $30 MAKE,
          $31 MODEL,
          $32 TRIM,
          $33 STYLE,
          $34 VEHICLE_TYPE,
          $35 BODY_TYPE,
          $36 BODY_SUBTYPE,
          $37 DOORS,
          REPLACE(SUBSTR($38, 2), ',', '') AS MSRP,
          $39 GVW_RANGE,
          REPLACE(REPLACE($40, ',', ''), ' lbs', '') AS GROSS_VEHICLE_WEIGHT_RATING,
          $41 TMP_TANK1_GAL,
          REPLACE(REPLACE($42, ',', ''), ' lbs', '') AS MAX_PAYLOAD,
          $43 TONNAGE,
          $44 DEF_ENGINE_ID,
          $45 DRIVE_TYPE,
          $46 FUEL_TYPE,
          $47 DEF_ENGINE_BLOCK,
          $48 DEF_ENGINE_CYLINDERS,
          $49 DEF_ENGINE_SIZE,
          $50 ENGINE_SIZE_UOM,
          $51 DEF_ENGINE_ASPIRATION,
          REPLACE($52, 'AUTO', '') DEF_TRANS_ID,
          $53 DEF_TRANS_SPEEDS,
          $54 AUTO_VALIDATION_DATE,
          $55 TRANSACTION_TYPE,
          $56 AUTO_TRANSACTION_DATE,
          $57 FIRST_SEEN,
          $58 LAST_SEEN,
          $59 RECORDID,
          $60 BROWSER,
          $61 DEVICE,
          $62 OS,
          $63 CARRIER_ROUTE,
          $64 MSA,
          REPLACE($65, 'MSA', '') MSA_CODE,
          $66 AGE_RANGE,
          CAST($67 AS STRING) AS ESTIMATED_INCOME,
          CAST($68 AS STRING) AS NET_WORTH,
          $69 ETHNIC_GROUP,
          $70 LANGUAGE,
          $71 DOB_MONTH,
          $72 DOB_DAY,
          $73 RELIGION,
          $74 YEARS_SINCE_HOME_WAS_BUILT,
          $75 NUMBER_OF_LINES_OF_CREDIT_TRADE_COUNTER,
          $76 BANK_CARD_HOLDER,
          $77 CREDIT_CARD_HOLDER_UNKNOWN_TYPE,
          $78 CREDIT_CARD_USER,
          $79 BANK_CARD_PRESENCE_IN_HOUSEHOLD,
          $80 EDUCATION,
          $81 PASS_PROSPECTOR_VALUE_HOME_VALUE_MORTGAGE_FILE,
          $82 _2ND_MOST_RECENT_MORTGAGE_DATE,
          $83 _2ND_MOST_RECENT_LENDER_NAME,
          $84 LOAN_TO_VALUE_RATIO,
          $85 _2ND_MORTGAGE_TYPE,
          $86 AIR_CONDITIONING,
          $87 POLITICAL_CHARITABLE_DONATION,
          $88 CONSUMER_ELECTRONICS,
          $89 ELECTRONICS_COMPUTING_AND_HOME_OFFICE,
          $90 INTEND_TO_PURCHASE_HDTV_SATELLITE_DISH,
          $91 READING_GENERAL,
          $92 READING_MAGAZINES,
          $93 LIFESTYLES_INTERESTS_AND_PASSIONS_RAFT_HOBBIES,
          $94 COOKING_GENERAL,
          $95 FOODS_NATURAL,
          $96 HEALTH_ENTHUSIAST,
          $97 HEALTH_MEDICAL,
          $98 COMP_OWN,
          $99 GAMBLERS,
          $100 OUTDOORSMEN,
          $101 HOME_FURNISHINGS_DECORATING,
          $102 ALCOHOL_USER,
          $103 SOURCE,
          $104 DATE_AND_TIME
        FROM @CONTROL_DB.PIXEL_RESOLUTION_STAGES."RESOLUTIONS_PIX_e0bfc1fc-8a06-48a8-b221-673653f0020e_STAGE"
    )
    FILE_FORMAT=(
    FORMAT_NAME=CONTROL_DB.FILE_FORMATS.CSV_FORMAT
    );
