SELECT * fROM AUDIENCELAB_INTERNAL_PROD.PUBLIC.B2B_EXPORT_TROVO;

TRUNCATE TABLE AUDIENCELAB_INTERNAL_PROD.PUBLIC.B2B_EXPORT_TROVO;


-- CSV is no good, we must try with json:
COPY INTO AUDIENCELAB_INTERNAL_PROD.PUBLIC.B2B_EXPORT_TROVO
FROM 
(   
    SELECT
        T.$1:"CONSUMERID"::NUMBER AS "ID",
        T.$1:"FIRST_NAME"::STRING AS "FIRST_NAME",
        T.$1:"LAST_NAME"::STRING AS "LAST_NAME",
        T.$1:"BUSINESS_EMAIL"::STRING AS "BUSINESS_EMAIL",
        T.$1:"SHA256_BUSINESS_EMAIL"::STRING AS "SHA256_BUSINESS_EMAIL",
        T.$1:"PROGRAMMATIC_BUSINESS_EMAILS"::STRING AS "PROGRAMMATIC_BUSINESS_EMAILS",
        T.$1:"PERSONAL_EMAIL"::STRING AS "PERSONAL_EMAIL",
        T.$1:"SHA256_PERSONAL_EMAIL"::STRING AS "SHA256_PERSONAL_EMAIL",
        T.$1:"JOB_TITLE"::STRING AS "JOB_TITLE",
        T.$1:"SENIORITY_LEVEL"::STRING AS "SENIORITY_LEVEL",
        T.$1:"DEPARTMENT"::STRING AS "DEPARTMENT",
        T.$1:"MOBILE_PHONE"::STRING AS "MOBILE_PHONE",
        T.$1:"DIRECT_NUMBER"::STRING AS "DIRECT_NUMBER",
        T.$1:"LINKEDIN_URL"::STRING AS "LINKEDIN_URL",
        T.$1:"PERSONAL_ADDRESS"::STRING AS "PERSONAL_ADDRESS",
        T.$1:"PERSONAL_ADDRESS_2"::STRING AS "PERSONAL_ADDRESS_2",
        T.$1:"PERSONAL_CITY"::STRING AS "PERSONAL_CITY",
        T.$1:"PERSONAL_STATE"::STRING AS "PERSONAL_STATE",
        T.$1:"PERSONAL_ZIP"::STRING AS "PERSONAL_ZIP",
        T.$1:"PERSONAL_ZIP4"::STRING AS "PERSONAL_ZIP4",
        T.$1:"PROFESSIONAL_ADDRESS"::STRING AS "PROFESSIONAL_ADDRESS",  -- Placeholder for missing column
        T.$1:"PROFESSIONAL_ADDRESS_2"::STRING AS "PROFESSIONAL_ADDRESS_2",  -- Placeholder for missing column
        T.$1:"PROFESSIONAL_CITY"::STRING AS "PROFESSIONAL_CITY",  -- Placeholder for missing column
        T.$1:"PROFESSIONAL_STATE"::STRING AS "PROFESSIONAL_STATE",  -- Placeholder for missing column
        T.$1:"PROFESSIONAL_ZIP"::STRING AS "PROFESSIONAL_ZIP",  -- Placeholder for missing column
        T.$1:"PROFESSIONAL_ZIP4"::STRING AS "PROFESSIONAL_ZIP4",  -- Placeholder for missing column
        T.$1:"COMPANY_NAME"::STRING AS "COMPANY_NAME",
        T.$1:"COMPANY_DOMAIN"::STRING AS "COMPANY_DOMAIN",
        T.$1:"COMPANY_PHONE"::STRING AS "COMPANY_PHONE",
        T.$1:"PRIMARY_INDUSTRY"::STRING AS "PRIMARY_INDUSTRY",
        T.$1:"COMPANY_SIC"::STRING AS "COMPANY_SIC",
        T.$1:"COMPANY_NAICS"::STRING AS "COMPANY_NAICS",
        T.$1:"COMPANY_ADDRESS"::STRING AS "COMPANY_ADDRESS",
        T.$1:"COMPANY_ADDRESS_2"::STRING AS "COMPANY_ADDRESS_2",
        T.$1:"COMPANY_CITY"::STRING AS "COMPANY_CITY",
        T.$1:"COMPANY_STATE"::STRING AS "COMPANY_STATE",
        T.$1:"COMPANY_ZIP"::STRING AS "COMPANY_ZIP",
        T.$1:"COMPANY_ZIP4"::STRING AS "COMPANY_ZIP4",
        T.$1:"COMPANY_LINKEDIN_URL"::STRING AS "COMPANY_LINKEDIN_URL",
        T.$1:"COMPANY_REVENUE"::STRING AS "COMPANY_REVENUE",
        T.$1:"COMPANY_EMPLOYEE_COUNT"::STRING AS "COMPANY_EMPLOYEE_COUNT",
        T.$1:"BUSINESS_EMAIL_VALIDATION_STATUS"::STRING AS "BUSINESS_EMAIL_VALIDATION_STATUS",
        T.$1:"BUSINESS_EMAIL_LAST_SEEN"::TIMESTAMP AS "BUSINESS_EMAIL_LAST_SEEN",
        T.$1:"COMPANY_LAST_UPDATED"::TIMESTAMP AS "COMPANY_LAST_UPDATED",
        T.$1:"JOB_TITLE_LAST_UPDATED"::TIMESTAMP AS "JOB_TITLE_LAST_UPDATED",
        T.$1:"LAST_UPDATED"::TIMESTAMP AS "LAST_UPDATED"
    FROM @FOUR_EYES.PUBLIC.AUDIENCELAB_BACKUP_STAGE/b2b_export_trovo/ AS T
)
FILE_FORMAT = (
    FORMAT_NAME = FOUR_EYES.PUBLIC.FOUR_EYES_JSON_FORMAT
);


