

GRANT USAGE ON WAREHOUSE AUDIENCE_WH TO ROLE PIXEL_AGENT;


GRANT USAGE ON WAREHOUSE ENRICHMENT_WH TO ROLE PIXEL_AGENT;


GRANT USAGE ON WAREHOUSE PIXEL_WH TO ROLE PIXEL_AGENT;


GRANT USAGE ON WAREHOUSE KEYWORD_WH TO ROLE PIXEL_AGENT;



// Data is present
SELECT * FROM FOUR_EYES.PUBLIC.PREMADE_4EYES_LITE
WHERE DATE IN ('2024-04-18') LIMIT 1000;

SELECT * FROM FOUR_EYES.PUBLIC.PREMADE_4EYES_LITE
WHERE DATE IN ('2024-04-10') LIMIT 1000;
