CREATE OR REPLACE STORAGE INTEGRATION FOUR_EYES_INTEGRATION
    TYPE=EXTERNAL_STAGE
    STORAGE_PROVIDER=S3
    ENABLED=TRUE
    STORAGE_AWS_ROLE_ARN='' -- a "snowflake" dedicated IAM user is needed, in AWS, to utilize this value
    STORAGE_ALLOWED_LOCATIONS=('');

CREATE OR REPLACE STORAGE INTEGRATION S3_INTEGRATION 
    TYPE=EXTERNAL_STAGE 
    STORAGE_PROVIDER='S3' 
    STORAGE_AWS_ROLE_ARN='' 
    STORAGE_AWS_EXTERNAL_ID='' 
    ENABLED=true 
    STORAGE_ALLOWED_LOCATIONS=('', '', '');






    CREATE OR REPLACE STORAGE INTEGRATION FOUR_EYES_INTEGRATION
    TYPE=EXTERNAL_STAGE
    STORAGE_PROVIDER=S3
    ENABLED=TRUE
    STORAGE_AWS_ROLE_ARN='' -- a "snowflake" dedicated IAM user is needed, in AWS, to utilize this value
    STORAGE_ALLOWED_LOCATIONS=('s3://audiencelab-4eyes/');








DESC STORAGE INTEGRATION FOUR_EYES_INTEGRATION;