-- PIXEL_AGENT:
GRANT USAGE ON DATABASE AUDIENCELAB_INTERNAL_PROD TO ROLE PIXEL_AGENT;
GRANT USAGE ON DATABASE TROVO TO ROLE PIXEL_AGENT;
GRANT USAGE ON DATABASE FOUR_EYES TO ROLE PIXEL_AGENT;

GRANT USAGE ON SCHEMA AUDIENCELAB_INTERNAL_PROD.PUBLIC TO ROLE PIXEL_AGENT;
GRANT USAGE ON SCHEMA TROVO.PUBLIC TO ROLE PIXEL_AGENT;
GRANT USAGE ON SCHEMA FOUR_EYES.PUBLIC TO ROLE PIXEL_AGENT;

--GRANT USAGE ON ALL TABLES IN SCHEMA AUDIENCELAB_INTERNAL_PROD.PUBLIC TO ROLE PIXEL_AGENT;
--GRANT USAGE ON ALL TABLES IN SCHEMA TROVO.PUBLIC TO ROLE PIXEL_AGENT;
--GRANT USAGE ON ALL TABLES IN SCHEMA FOUR_EYES.PUBLIC TO ROLE PIXEL_AGENT;

GRANT SELECT ON ALL TABLES IN SCHEMA AUDIENCELAB_INTERNAL_PROD.PUBLIC TO ROLE PIXEL_AGENT;
GRANT SELECT ON ALL TABLES IN SCHEMA TROVO.PUBLIC TO ROLE PIXEL_AGENT;
GRANT SELECT ON ALL TABLES IN SCHEMA FOUR_EYES.PUBLIC TO ROLE PIXEL_AGENT;

GRANT SELECT ON FUTURE TABLES IN SCHEMA AUDIENCELAB_INTERNAL_PROD.PUBLIC TO ROLE PIXEL_AGENT;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TROVO.PUBLIC TO ROLE PIXEL_AGENT;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FOUR_EYES.PUBLIC TO ROLE PIXEL_AGENT;

-- STATISTICS USER:
GRANT USAGE ON DATABASE STATISTICS TO ROLE STATISTICS_USER;

GRANT USAGE ON SCHEMA STATISTICS.PUBLIC TO ROLE STATISTICS_USER;

--GRANT USAGE ON ALL TABLES IN SCHEMA STATISTICS.PUBLIC TO ROLE STATISTICS_USER;

GRANT SELECT ON ALL TABLES IN SCHEMA STATISTICS.PUBLIC TO ROLE STATISTICS_USER;

GRANT SELECT ON FUTURE TABLES IN SCHEMA STATISTICS.PUBLIC TO ROLE STATISTICS_USER;