// 0) Check tables' contents:
SELECT * FROM TROVO.PUBLIC.IP_HEM_1_8_0 LIMIT 100;
SELECT SHA256_PERSONAL_EMAIL FROM AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON LIMIT 3;


// 1) Create table with TEST data
//CREATE OR REPLACE TRANSIENT TABLE TROVO.TEST.BIG_IP_TO_UPID
//AS
//SELECT
//     IP_HEM."IP_ADRESS" AS "IP",
 //     IP_HEM."SHA256_LC_HEM" AS "SHA256",
 //     U_PERSON.UP_ID AS "UP_ID"
 //   FROM
 //     TROVO.TEST.UNIVERSAL_PERSON_TEST AS "U_PERSON"
 //   INNER JOIN
 //     TROVO.TEST.IP_HEM_ARRAY_TEST AS "IP_HEM"
 //    ON IP_HEM."SHA256_LC_HEM" = U_PERSON."SHA256_PERSONAL_EMAIL";


// Altered Query:
CREATE OR REPLACE TRANSIENT TABLE TROVO.TEST.BIG_IP_TO_UPID AS
SELECT
    IP,
    SHA256,
    UP_ID,
    ARRAY_VALUE AS HEM_ARRAY_VALUE
FROM (
    SELECT
        IP_HEM."IP_ADRESS" AS IP,
        IP_HEM."SHA256_LC_HEM" AS SHA256,
        U_PERSON.UP_ID AS UP_ID,
        IP_HEM.HEM_ARRAY[1] AS ARRAY_VALUE
    FROM
        TROVO.TEST.UNIVERSAL_PERSON_TEST AS U_PERSON
    INNER JOIN
        TROVO.TEST.IP_HEM_ARRAY_TEST AS IP_HEM
    ON
        IP_HEM."SHA256_LC_HEM" = U_PERSON."SHA256_PERSONAL_EMAIL"
    WHERE ARRAY_SIZE(IP_HEM.HEM_ARRAY) >= 1
    UNION ALL
    SELECT
        IP_HEM."IP_ADRESS" AS IP,
        IP_HEM."SHA256_LC_HEM" AS SHA256,
        U_PERSON.UP_ID AS UP_ID,
        IP_HEM.HEM_ARRAY[2] AS ARRAY_VALUE
    FROM
        TROVO.TEST.UNIVERSAL_PERSON_TEST AS U_PERSON
    INNER JOIN
        TROVO.TEST.IP_HEM_ARRAY_TEST AS IP_HEM
    ON
        IP_HEM."SHA256_LC_HEM" = U_PERSON."SHA256_PERSONAL_EMAIL"
    WHERE ARRAY_SIZE(IP_HEM.HEM_ARRAY) >= 2
    UNION ALL
    SELECT
        IP_HEM."IP_ADRESS" AS IP,
        IP_HEM."SHA256_LC_HEM" AS SHA256,
        U_PERSON.UP_ID AS UP_ID,
        IP_HEM.HEM_ARRAY[3] AS ARRAY_VALUE
    FROM
        TROVO.TEST.UNIVERSAL_PERSON_TEST AS U_PERSON
    INNER JOIN
        TROVO.TEST.IP_HEM_ARRAY_TEST AS IP_HEM
    ON
        IP_HEM."SHA256_LC_HEM" = U_PERSON."SHA256_PERSONAL_EMAIL"
    WHERE ARRAY_SIZE(IP_HEM.HEM_ARRAY) >= 3
);





// Alternative query, matching on more than one SHA (too slow):
CREATE OR REPLACE TRANSIENT TABLE TROVO.TEST.BIG_IP_TO_UPID_ALTERNATIVE
AS
SELECT
     IP_HEM."IP_ADRESS" AS "IP",
      IP_HEM."SHA256_LC_HEM" AS "SHA256",
      U_PERSON.UP_ID AS "UP_ID"
    FROM
      TROVO.TEST.UNIVERSAL_PERSON_TEST AS "U_PERSON"
    INNER JOIN
      TROVO.TEST.IP_HEM_ARRAY_TEST AS "IP_HEM"
     ON (IP_HEM.HEM_ARRAY[0] = U_PERSON."SHA256_PERSONAL_EMAIL")
     OR (IP_HEM.HEM_ARRAY[1] = U_PERSON."SHA256_PERSONAL_EMAIL")
     OR (IP_HEM.HEM_ARRAY[2] = U_PERSON."SHA256_PERSONAL_EMAIL")
     OR (IP_HEM.HEM_ARRAY[3] = U_PERSON."SHA256_PERSONAL_EMAIL");



// Alternative query, matching on a single SHA, inside of the array:
CREATE OR REPLACE TRANSIENT TABLE TROVO.TEST.BIG_IP_TO_UPID_ALTERNATIVE
AS
SELECT
     IP_HEM."IP_ADRESS" AS "IP",
      IP_HEM."SHA256_LC_HEM" AS "SHA256",
      U_PERSON.UP_ID AS "UP_ID"
    FROM
      TROVO.TEST.UNIVERSAL_PERSON_TEST AS "U_PERSON"
    INNER JOIN
      TROVO.TEST.IP_HEM_ARRAY_TEST AS "IP_HEM"
     ON (IP_HEM.HEM_ARRAY[0] = U_PERSON."SHA256_PERSONAL_EMAIL");


USE SCHEMA TROVO.TEST;

// Alternative query, matching on four first SHAs, inside of the array:
CREATE OR REPLACE TRANSIENT TABLE TROVO.TEST.BIG_IP_TO_UPID_ALTERNATIVE AS
SELECT
    IP_HEM."IP_ADRESS" AS "IP",
    IP_HEM."SHA256_LC_HEM" AS "SHA256",
    U_PERSON.UP_ID AS "UP_ID"
FROM
    TROVO.TEST.UNIVERSAL_PERSON_TEST AS U_PERSON
INNER JOIN (
    SELECT
        t1."IP_ADRESS",
        t1."SHA256_LC_HEM",
        t2.VALUE::string AS HEM_VALUE
    FROM
        TROVO.TEST.IP_HEM_ARRAY_TEST AS t1,
        LATERAL FLATTEN(t1.HEM_ARRAY) t2
    WHERE
        ARRAY_POSITION(t2.VALUE, t1.HEM_ARRAY) <= 3 -- Limit to first four elements
) AS IP_HEM
ON
    U_PERSON.SHA256_PERSONAL_EMAIL = IP_HEM.HEM_VALUE;





// Testing with live data:
CREATE OR REPLACE TRANSIENT TABLE TROVO.PUBLIC.BIG_IP_TO_UPID AS
SELECT
    IP_HEM."IP_ADRESS" AS "IP",
    IP_HEM."SHA256_LC_HEM" AS "SHA256",
    U_PERSON.UP_ID AS "UP_ID"
FROM
    AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON AS U_PERSON
INNER JOIN (
    SELECT
        t1."IP_ADRESS",
        t1."SHA256_LC_HEM",
        t2.VALUE::string AS HEM_VALUE
    FROM
        TROVO.PUBLIC.IP_HEM_18_0_HEM_ARRAY_VERSION AS t1,
        LATERAL FLATTEN(t1.HEM_ARRAY) t2
    WHERE
        ARRAY_POSITION(t2.VALUE, t1.HEM_ARRAY) <= 15 -- Limit to first four elements
) AS IP_HEM
ON
    U_PERSON.SHA256_PERSONAL_EMAIL = IP_HEM.HEM_VALUE;





SELECT COUNT(*) FROM TROVO.TEST.BIG_IP_TO_UPID_TEST;









SELECT * FROM TROVO.TEST.UNIVERSAL_PERSON_TEST LIMIT 3;



// Original query:
CREATE OR REPLACE TRANSIENT TABLE TROVO.TEST.SMALL_IP_TO_UPID
AS
SELECT
     IP_HEM."IP_ADRESS" AS "IP",
      IP_HEM."SHA256_LC_HEM" AS "SHA256",
      U_PERSON.UP_ID AS "UP_ID"
    FROM
      TROVO.TEST.UNIVERSAL_PERSON_TEST AS "U_PERSON"
    INNER JOIN
      TROVO.TEST.IP_HEM_ARRAY_TEST AS "IP_HEM"
     ON IP_HEM."SHA256_LC_HEM" = U_PERSON."SHA256_PERSONAL_EMAIL";




d2, 55, f7.



// Check Tables' contents: 
//SELECT * FROM TROVO.TEST.BIG_IP_TO_UPID LIMIT 1000;

//SELECT * FROM TROVO.TEST.IP_HEM_ARRAY_TEST WHERE SHA256_LC_HEM='66b0a20eafd471f75a7e6a4920e849ddbd5a42bb81d2f3c4009192418a6f9799';

SELECT * FROM TROVO.TEST.IP_HEM_ARRAY_TEST WHERE SHA256_LC_HEM='e275873ab82c0005cc1c48628fcf77bce4cabe5fe51718e24a921525f0c2a610';

SELECT * FROM TROVO.TEST.BIG_IP_TO_UPID WHERE SHA256='e275873ab82c0005cc1c48628fcf77bce4cabe5fe51718e24a921525f0c2a610';

SELECT * FROM TROVO.TEST.SMALL_IP_TO_UPID LIMIT 100;

SELECT * FROM TROVO.TEST.SMALL_IP_TO_UPID WHERE SHA256='66b0a20eafd471f75a7e6a4920e849ddbd5a42bb81d2f3c4009192418a6f9799';


SELECT * FROM TROVO.PUBLIC.BIG_IP_TO_UPID WHERE SHA256='e275873ab82c0005cc1c48628fcf77bce4cabe5fe51718e24a921525f0c2a610';






SELECT * FROM TROVO.PUBLIC.IP_HEM_18_0_HEM_ARRAY_VERSION WHERE IP_ADRESS='108.191.67.146';


SELECT * FROM TROVO.PUBLIC.BIG_IP_TO_UPID WHERE IP='108.191.67.146';





SELECT * FROM TROVO.PUBLIC.BIG_IP_TO_UPID LIMIT 1000;










select consumer.* FROM TROVO.PUBLIC.BIG_IP_TO_UPID ic
    INNER JOIN AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON consumer ON ic.up_id=consumer.up_id
    WHERE ip = '69.127.30.204' limit 1;




    
select consumer.* FROM TROVO.PUBLIC.BIG_IP_TO_UPID ic
    INNER JOIN AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON consumer ON ic.up_id=consumer.up_id
    WHERE ip = '206.123.211.186' limit 1;





select consumer.* FROM TROVO.PUBLIC.BIG_IP_TO_UPID ic
    INNER JOIN AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON consumer ON ic.up_id=consumer.up_id
    WHERE ip = '173.93.248.92' limit 1;




select consumer.* FROM TROVO.PUBLIC.BIG_IP_TO_UPID ic
    INNER JOIN AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON consumer ON ic.up_id=consumer.up_id
    WHERE ip = '75.169.10.69' limit 1;





    select consumer.* FROM TROVO.PUBLIC.BIG_IP_TO_UPID ic
    INNER JOIN AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON consumer ON ic.up_id=consumer.up_id
    WHERE ip = '108.24.1.170' limit 1;




select consumer.* FROM TROVO.PUBLIC.BIG_IP_TO_UPID ic
    INNER JOIN AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON consumer ON ic.up_id=consumer.up_id
    WHERE ip = '68.50.173.58' limit 1;




select consumer.* FROM TROVO.PUBLIC.BIG_IP_TO_UPID ic
    INNER JOIN AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON consumer ON ic.up_id=consumer.up_id
    WHERE ip = '24.246.225.150' limit 1;






select consumer.* FROM TROVO.PUBLIC.BIG_IP_TO_UPID ic
    INNER JOIN AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON consumer ON ic.up_id=consumer.up_id
    WHERE ip = '98.97.20.168' limit 1;



select consumer.* FROM TROVO.PUBLIC.BIG_IP_TO_UPID ic
    INNER JOIN AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON consumer ON ic.up_id=consumer.up_id
    WHERE ip = '76.98.79.120' limit 1;



    select consumer.* FROM TROVO.PUBLIC.BIG_IP_TO_UPID ic
    INNER JOIN AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON consumer ON ic.up_id=consumer.up_id
    WHERE ip = '76.104.113.78' limit 1;




select consumer.* FROM TROVO.PUBLIC.BIG_IP_TO_UPID ic
    INNER JOIN AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON consumer ON ic.up_id=consumer.up_id
    WHERE ip = '67.180.59.165' limit 1;














select consumer.* FROM TROVO.PUBLIC.BIG_IP_TO_UPID ic
    INNER JOIN AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON consumer ON ic.up_id=consumer.up_id
    WHERE ip = '40.94.28.74' limit 1;





SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY LIMIT 1;




SELECT
  AVG(total_elapsed_time) AS average_query_time
FROM
  SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE
  database_name = 'TROVO'
  AND schema_name = 'PUBLIC'
  AND table_name = 'BIG_IP_TO_UPID'
  AND start_time >= (SELECT CREATED::timestamp FROM trovo.information_schema.tables WHERE TABLE_NAME = 'BIG_IP_TO_UPID');




select consumer.* FROM TROVO.PUBLIC.BIG_IP_TO_UPID ic
    INNER JOIN AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON consumer ON ic.up_id=consumer.up_id
    WHERE ip = '204.128.192.33' limit 1;





  select consumer.* FROM TROVO.PUBLIC.BIG_IP_TO_UPID ic
    INNER JOIN AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON consumer ON ic.up_id=consumer.up_id
    WHERE ip = '166.199.168.37' limit 1;


    select consumer.* FROM TROVO.PUBLIC.BIG_IP_TO_UPID ic
    INNER JOIN AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON consumer ON ic.up_id=consumer.up_id
    WHERE ip = '99.98.148.194' limit 1





    select consumer.* FROM TROVO.PUBLIC.BIG_IP_TO_UPID ic
    INNER JOIN AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON consumer ON ic.up_id=consumer.up_id
    WHERE ip = '97.106.180.234' limit 1;




select consumer.* FROM TROVO.PUBLIC.BIG_IP_TO_UPID ic
    INNER JOIN AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON consumer ON ic.up_id=consumer.up_id
    WHERE ip = '136.38.158.122' limit 1;





select consumer.* FROM TROVO.PUBLIC.BIG_IP_TO_UPID ic
    INNER JOIN AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON consumer ON ic.up_id=consumer.up_id
    WHERE ip = '98.117.8.51' limit 1;





select consumer.* FROM TROVO.PUBLIC.BIG_IP_TO_UPID ic
    INNER JOIN AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON consumer ON ic.up_id=consumer.up_id
    WHERE ip = '67.187.209.162' limit 1;



select consumer.* FROM TROVO.PUBLIC.BIG_IP_TO_UPID ic
    INNER JOIN AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON consumer ON ic.up_id=consumer.up_id
    WHERE ip = '174.45.28.251' limit 1;




    select consumer.* FROM TROVO.PUBLIC.BIG_IP_TO_UPID ic
    INNER JOIN AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON consumer ON ic.up_id=consumer.up_id
    WHERE ip = '104.28.92.230' limit 1;




    SELECT MIN(DATE) as earliestDate, MAX(DATE) as latestDate FROM FOUR_EYES.PUBLIC.PREMADE_4EYES_LITE















    SELECT PARSE_JSON(system$estimate_query_acceleration('01b2acf1-0001-b632-0003-fe16458ed9e2'));



USE SCHEMA TROVO.PUBLIC;


SELECT SYSTEM$CLUSTERING_INFORMATION('BIG_IP_TO_UPID','(UP_ID)');







// 1) clustering: we can't, too high cardinality 



// 2) query acceleration service: ineligible 



// 3) search optimization service: not enough of a boost



select consumer.* FROM TROVO.PUBLIC.BIG_IP_TO_UPID ic
    INNER JOIN AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON consumer ON ic.up_id=consumer.up_id
    WHERE ip = '162.219.136.43' limit 1;








select consumer.* FROM TROVO.PUBLIC.BIG_IP_TO_UPID ic
    INNER JOIN AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON consumer ON ic.up_id=consumer.up_id
    WHERE ip = '156.99.196.177' limit 1;



select consumer.* FROM TROVO.PUBLIC.BIG_IP_TO_UPID ic
    INNER JOIN AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON consumer ON ic.up_id=consumer.up_id
    WHERE ip = '174.195.194.129' limit 1;
    

select consumer.* FROM TROVO.PUBLIC.BIG_IP_TO_UPID ic
    INNER JOIN AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON consumer ON ic.up_id=consumer.up_id
    WHERE ip = '108.28.180.178' limit 1;








