// THIS WORKSHEET NEEDS TO BE ADAPTED TO THE AUDIENCELAB DATABASE:

// Create Transient Table for Pixel Resolutions
CREATE TRANSIENT TABLE STATISTICS.PUBLIC.RESOLVED_TROVO_FEED (
    _ID STRING,
    PARTNERUID STRING,
    PIXEL_ID STRING,
    SHA256 STRING,
    _V STRING,
    CELL_PHONE_1 STRING,
    CELL_PHONE_2 STRING,
    CONSUMER_ID STRING,
    COOKIE_SYNC STRING,
    CREATED_AT TIMESTAMP_TZ,
    UPDATED_AT TIMESTAMP_TZ,
    EMAIL_ADDRESS_1 STRING,
    FIRST_NAME STRING,
    INDIVIDUALID STRING,
    LAST_NAME STRING
);

ALTER TABLE STATISTICS.PUBLIC.RESOLVED_TROVO_FEED
SET DATA_RETENTION_TIME_IN_DAYS=0;



// Create Storage Integration for Track Folder
// CREATE OR REPLACE STORAGE INTEGRATION PIXEL_RESOLUTION_INTEGRATION
//    TYPE=EXTERNAL_STAGE
//   STORAGE_PROVIDER=S3
//    ENABLED=TRUE
//    STORAGE_AWS_ROLE_ARN='arn:aws:iam::269021562924:role/snowflake-test-role-6' -- a "snowflake" dedicated IAM user is needed, in AWS, to utilize this value
//    STORAGE_ALLOWED_LOCATIONS=('s3://snowflake-task-test-bucket/PIXEL_RESOLUTIONS_NEW');


// DESC STORAGE INTEGRATION PIXEL_RESOLUTION_INTEGRATION;

// Create PIXEL_RESOLUTION File Format:
CREATE OR REPLACE FILE FORMAT STATISTICS.PUBLIC.PIXEL_RESOLUTION_CSV_FORMAT
    TYPE=CSV,
    FIELD_DELIMITER=';',
    SKIP_HEADER=1,
    NULL_IF=('NULL', 'null', '"null"')
    -- FIELD_OPTIONALLY_ENCLOSED_BY='"'
    ;

// Create S3 Stage
CREATE OR REPLACE STAGE STATISTICS.PUBLIC.PIXEL_RESOLUTION_STAGE
    url='s3://audiencelab-visits/resolvedTrovoFeed'
    STORAGE_INTEGRATION=STATISTICS_INTEGRATION
    FILE_FORMAT=(
        FORMAT_NAME='STATISTICS.PUBLIC.PIXEL_RESOLUTION_CSV_FORMAT'
    );



// Copy data from PIXEL_RESOLUTIONS S3 stage into RESOLVED_TROVO_FEED Transient Table
COPY INTO STATISTICS.PUBLIC.RESOLVED_TROVO_FEED
FROM (
SELECT 
REPLACE(T.$1, '"', '') AS _ID,
REPLACE(T.$2, '"', '') AS PARTNERUID,
REPLACE(T.$3, '"', '') AS PIXEL_ID,
REPLACE(T.$4, '"', '') AS SHA256,
REPLACE(T.$5, '"', '') AS _V,
REPLACE(T.$6, '"', '') AS CELL_PHONE_1,
REPLACE(T.$7, '"', '') AS CELL_PHONE_2,
REPLACE(T.$8, '"', '') AS CONSUMER_ID,
REPLACE(T.$9, '"', '') AS COOKIE_SYNC,
CONCAT(TO_TIMESTAMP_NTZ(CONCAT(SUBSTR(T.$10, 13, 4), '-', 
CASE SUBSTR(T.$10, 6, 3)
                WHEN 'Jan' THEN '01'
                WHEN 'Feb' THEN '02'
                WHEN 'Mar' THEN '03'
                WHEN 'Apr' THEN '04'
                WHEN 'May' THEN '05'
                WHEN 'Jun' THEN '06'
                WHEN 'Jul' THEN '07'
                WHEN 'Aug' THEN '08'
                WHEN 'Sep' THEN '09'
                WHEN 'Oct' THEN '10'
                WHEN 'Nov' THEN '11'
                WHEN 'Dec' THEN '12'
            END, '-',
SUBSTR(T.$10, 10, 2), ' ', SUBSTR(T.$10, 18, 8)) ), ' ', SUBSTR(T.$10, 30, 5)) AS CREATED_AT,
CONCAT(TO_TIMESTAMP_NTZ(CONCAT(SUBSTR(T.$11, 13, 4), '-', 
CASE SUBSTR(T.$11, 6, 3)
                WHEN 'Jan' THEN '01'
                WHEN 'Feb' THEN '02'
                WHEN 'Mar' THEN '03'
                WHEN 'Apr' THEN '04'
                WHEN 'May' THEN '05'
                WHEN 'Jun' THEN '06'
                WHEN 'Jul' THEN '07'
                WHEN 'Aug' THEN '08'
                WHEN 'Sep' THEN '09'
                WHEN 'Oct' THEN '10'
                WHEN 'Nov' THEN '11'
                WHEN 'Dec' THEN '12'
            END, '-',
SUBSTR(T.$11, 10, 2), ' ', SUBSTR(T.$11, 18, 8)) ), ' ', SUBSTR(T.$11, 30, 5)) AS UPDATED_AT,
REPLACE(T.$12, '"', '') AS EMAIL_ADDRESS_1,
REPLACE(T.$13, '"', '') AS FIRST_NAME,
REPLACE(T.$14, '"', '') AS INDIVIDUALID,
REPLACE(T.$15, '"', '') AS LAST_NAME

FROM @STATISTICS.PUBLIC.PIXEL_RESOLUTION_STAGE/ T
)
ON_ERROR=CONTINUE;



LIST @STATISTICS.PUBLIC.PIXEL_RESOLUTION_STAGE;

// 19.813.711 rows
SELECT COUNT(*) FROM @STATISTICS.PUBLIC.PIXEL_RESOLUTION_STAGE;

// 19813711 rows
SELECT COUNT(*) FROM STATISTICS.PUBLIC.RESOLVED_TROVO_FEED;


// Validate RESOLVED_TROVO_FEED table
SELECT * FROM STATISTICS.PUBLIC.RESOLVED_TROVO_FEED LIMIT 10000;





// TRUNCATE TABLE xxxxx.PUBLIC.RESOLVED_TROVO_FEED;





// Create task for monthly RESOLVED_TROVO_FEED copying:
CREATE OR REPLACE TASK STATISTICS.PUBLIC.RESOLVED_TROVO_FEED_TASK
    WAREHOUSE=DATALOADER
    SCHEDULE='USING CRON 0 0 17 * * America/Chicago'
    USER_TASK_TIMEOUT_MS=36000000
    AS 
COPY INTO STATISTICS.PUBLIC.RESOLVED_TROVO_FEED
FROM (
SELECT 
REPLACE(T.$1, '"', '') AS _ID,
REPLACE(T.$2, '"', '') AS PARTNERUID,
REPLACE(T.$3, '"', '') AS PIXEL_ID,
REPLACE(T.$4, '"', '') AS SHA256,
REPLACE(T.$5, '"', '') AS _V,
REPLACE(T.$6, '"', '') AS CELL_PHONE_1,
REPLACE(T.$7, '"', '') AS CELL_PHONE_2,
REPLACE(T.$8, '"', '') AS CONSUMER_ID,
REPLACE(T.$9, '"', '') AS COOKIE_SYNC,
CONCAT(TO_TIMESTAMP_NTZ(CONCAT(SUBSTR(T.$10, 13, 4), '-', 
CASE SUBSTR(T.$10, 6, 3)
                WHEN 'Jan' THEN '01'
                WHEN 'Feb' THEN '02'
                WHEN 'Mar' THEN '03'
                WHEN 'Apr' THEN '04'
                WHEN 'May' THEN '05'
                WHEN 'Jun' THEN '06'
                WHEN 'Jul' THEN '07'
                WHEN 'Aug' THEN '08'
                WHEN 'Sep' THEN '09'
                WHEN 'Oct' THEN '10'
                WHEN 'Nov' THEN '11'
                WHEN 'Dec' THEN '12'
            END, '-',
SUBSTR(T.$10, 10, 2), ' ', SUBSTR(T.$10, 18, 8)) ), ' ', SUBSTR(T.$10, 30, 5)) AS CREATED_AT,
CONCAT(TO_TIMESTAMP_NTZ(CONCAT(SUBSTR(T.$11, 13, 4), '-', 
CASE SUBSTR(T.$11, 6, 3)
                WHEN 'Jan' THEN '01'
                WHEN 'Feb' THEN '02'
                WHEN 'Mar' THEN '03'
                WHEN 'Apr' THEN '04'
                WHEN 'May' THEN '05'
                WHEN 'Jun' THEN '06'
                WHEN 'Jul' THEN '07'
                WHEN 'Aug' THEN '08'
                WHEN 'Sep' THEN '09'
                WHEN 'Oct' THEN '10'
                WHEN 'Nov' THEN '11'
                WHEN 'Dec' THEN '12'
            END, '-',
SUBSTR(T.$11, 10, 2), ' ', SUBSTR(T.$11, 18, 8)) ), ' ', SUBSTR(T.$11, 30, 5)) AS UPDATED_AT,
REPLACE(T.$12, '"', '') AS EMAIL_ADDRESS_1,
REPLACE(T.$13, '"', '') AS FIRST_NAME,
REPLACE(T.$14, '"', '') AS INDIVIDUALID,
REPLACE(T.$15, '"', '') AS LAST_NAME
FROM @STATISTICS.PUBLIC.PIXEL_RESOLUTION_STAGE/ T
)
ON_ERROR=CONTINUE;



ALTER TASK STATISTICS.PUBLIC.RESOLVED_TROVO_FEED_TASK RESUME;





SELECT COUNT(*) FROM STATISTICS.PUBLIC.RESOLVED_TROVO_FEED 
WHERE DATE(CREATED_AT)= '2024-03-19';







GRANT USAGE ON DATABASE STATISTICS TO ROLE PIXEL_AGENT;
GRANT USAGE ON SCHEMA STATISTICS.PUBLIC TO ROLE PIXEL_AGENT;


GRANT SELECT ON TABLE STATISTICS.PUBLIC.RESOLVED_TROVO_FEED TO ROLE PIXEL_AGENT;
GRANT SELECT ON FUTURE TABLES IN SCHEMA STATISTICS.PUBLIC TO ROLE PIXEL_AGENT;




USE ROLE PIXEL_AGENT;






GRANT USAGE ON DATABASE STATISTICS TO ROLE AUDIENCEUSER;
GRANT USAGE ON SCHEMA STATISTICS.PUBLIC TO ROLE AUDIENCEUSER;


GRANT SELECT ON TABLE STATISTICS.PUBLIC.RESOLVED_TROVO_FEED TO ROLE AUDIENCEUSER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA STATISTICS.PUBLIC TO ROLE AUDIENCEUSER;




USE ROLE PIXEL_AGENT;

