
-- Table should have 350.8M ROWS.
-- Fill AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON with data:
 COPY INTO AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON
    FROM (
        SELECT 
        CAST(T.$1 AS NUMBER)  AS ID,
        T.$2 AS FIRST_NAME,
        T.$3 AS LAST_NAME,
        T.$4 AS BUSINESS_EMAIL,
        T.$5 AS SHA256_BUSINESS_EMAIL,
        T.$6 AS PROGRAMMATIC_BUSINESS_EMAILS,
        T.$7 AS MOBILE_PHONE,
        T.$8 AS DIRECT_NUMBER,
        T.$9 AS PERSONAL_PHONE,
        T.$10 AS LINKEDIN_URL,
        T.$11 AS PERSONAL_ADDRESS,
        T.$12 AS PERSONAL_ADDRESS_2,
        T.$13 AS PERSONAL_CITY,
        T.$14 AS PERSONAL_STATE,
        T.$15 AS PERSONAL_ZIP,
        T.$16 AS PERSONAL_ZIP4,
        T.$17 AS PERSONAL_EMAIL,
        T.$18 AS SHA256_PERSONAL_EMAIL,
        T.$19 AS ADDITIONAL_PERSONAL_EMAILS,
        T.$20 AS GENDER,
        T.$21 AS AGE_RANGE,
        T.$22 AS MARRIED,
        T.$23 AS CHILDREN,
        T.$24 AS INCOME_RANGE,
        T.$25 AS NET_WORTH,
        T.$26 AS HOMEOWNER,
        T.$27 AS JOB_TITLE,
        T.$28 AS SENIORITY_LEVEL,
        T.$29 AS DEPARTMENT,
        T.$30 AS PROFESSIONAL_ADDRESS,
        T.$31 AS PROFESSIONAL_ADDRESS2,
        T.$32 AS PROFESSIONAL_CITY,
        T.$33 AS PROFESSIONAL_STATE,
        T.$34 AS PROFESSIONAL_ZIP,
        T.$35 AS PROFESSIONAL_ZIP4,
        T.$36 AS COMPANY_NAME,
        T.$37 AS COMPANY_DOMAIN,
        T.$38 AS COMPANY_PHONE,
        T.$39 AS COMPANY_SIC,
        T.$40 AS COMPANY_ADDRESS,
        T.$41 AS COMPANY_CITY,
        T.$42 AS COMPANY_STATE,
        T.$43 AS COMPANY_ZIP,
        T.$44 AS COMPANY_LINKEDIN_URL,
        T.$45 AS COMPANY_REVENUE,
        T.$46 AS COMPANY_EMPLOYEE_COUNT,
        T.$47 AS PRIMARY_INDUSTRY,
        T.$48 AS BUSINESS_EMAIL_VALIDATION_STATUS,
        TO_TIMESTAMP(T.$49) AS BUSINESS_EMAIL_LAST_SEEN, -- date
        T.$50 AS PERSONAL_EMAIL_LAST_SEEN_VALIDATION_STATUS,
        TO_TIMESTAMP(T.$51) AS PERSONAL_EMAIL_LAST_SEEN, -- date
        TO_TIMESTAMP(T.$52) AS COMPANY_LAST_UPDATED, -- date
        TO_TIMESTAMP(T.$53) AS JOB_TITLE_LAST_UPDATED, -- date
        TO_TIMESTAMP(T.$54) AS LAST_UPDATED, -- date
        T.$55 AS COMPANY_DESCRIPTIONS, 
        T.$56 AS RELATED_DOMAINS,
        T.$57 AS DIRECT_NUMBER_DNC_FLAG,
        T.$58 AS PERSONAL_PHONE_DNC_FLAG,
        T.$59 AS MOBILE_PHONE_DNC_FLAG,
        T.$60 AS COMPANY_PHONE_DNC_FLAG,
        T.$61 AS CREDIT_RATING,
        CAST(T.$62 AS NUMBER) AS EXACT_AGE,
        T.$63 AS UP_ID
        FROM @FOUR_EYES.PUBLIC.AUDIENCELAB_BACKUP_STAGE/universal_person AS T
    );


TRUNCATE TABLE AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON;


SELECT * FROM AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON LIMIT 10000;




 COPY INTO AUDIENCELAB_INTERNAL_PROD.PUBLIC.UNIVERSAL_PERSON
 FROM 
 (
 SELECT
 *
 FROM
 @FOUR_EYES.PUBLIC.FOUR_EYES_UNIVERSAL_PERSON_STAGE/data_0_0_0.snappy.parquet
 );
 


-- Fill AUDIENCELAB_INTERNAL_PROD.PUBLIC.CONSUMER_B2C_FULL with data:
    COPY INTO AUDIENCELAB_INTERNAL_PROD.PUBLIC.CONSUMER_B2C_FULL
    FROM 
    (
        SELECT 
        CAST(T.$1 AS NUMBER)  AS ID,
        T.$2 AS FIRST_NAME,
        T.$3 AS LAST_NAME,
        T.$4 AS PERSONAL_EMAIL,
        T.$5 AS SHA256_PERSONAL_EMAIL,
        T.$6 AS ADDITIONAL_PERSONAL_EMAILS,
        T.$7 AS ADDRESS,
        T.$8 AS ADDRESS_2,
        T.$9 AS LATITUDE,
        T.$10 AS LONGITUDE,
        T.$11 AS MOBILE_PHONE,
        T.$12 AS PERSONAL_PHONE,
        T.$13 AS DPV_CODE,
        T.$14 AS GENDER,
        T.$15 AS AGE_RANGE,
        T.$16 AS MARRIED,
        T.$17 AS CHILDREN,
        T.$18 AS INCOME_RANGE,
        T.$19 AS NET_WORTH,
        T.$20 AS HOMEOWNER,
        T.$21 AS PERSONAL_EMAIL_LAST_SEEN_VALIDATION_STATUS,
        TO_TIMESTAMP(T.$22) AS PERSONAL_EMAIL_LAST_SEEN,
        T.$23 AS CONSUMER_ADDRESS,
        T.$24 AS ADULTS_F_18_24,
        T.$25 AS ADULTS_F_25_34,
        T.$26 AS ADULTS_F_35_44,
        T.$27 AS ADULTS_F_45_54,
        T.$28 AS ADULTS_F_55_64,
        T.$29 AS ADULTS_F_65_74,
        T.$30 AS ADULTS_F_75PLUS,
        T.$31 AS ADULTS_M_18_24,
        T.$32 AS ADULTS_M_25_34,
        T.$33 AS ADULTS_M_35_44,
        T.$34 AS ADULTS_M_45_54,
        T.$35 AS ADULTS_M_55_64,
        T.$36 AS ADULTS_M_65_74,
        T.$37 AS ADULTS_M_75PLUS,
        T.$38 AS ADULTS_U_18_24,
        T.$39 AS ADULTS_U_25_34,
        T.$40 AS ADULTS_U_35_44,
        T.$41 AS ADULTS_U_45_54,
        T.$42 AS ADULTS_U_55_64,
        T.$43 AS ADULTS_U_65_74,
        T.$44 AS ADULTS_U_75PLUS,
        T.$45 AS AUTO_BODY_TYPE,
        T.$46 AS AUTO_DEF_ENGINE_CYLINDERS,
        T.$47 AS AUTO_DEF_TRANS_TYPE,
        T.$48 AS AUTO_FUEL_TYPE,
        T.$49 AS AUTO_GVW_RANGE,
        T.$50 AS AUTO_MAKE,
        T.$51 AS AUTO_MFG_CODE,
        T.$52 AS AUTO_MSRP,
        T.$53 AS AUTO_STYLE,
        T.$54 AS AUTO_VEHICLE_TYPE,
        T.$55 AS AUTO_VIN,
        T.$56 AS AUTO_YEAR,
        T.$57 AS AUTOALARMTYPE,
        T.$58 AS AUTOANNUALMILES,
        T.$59 AS AUTOCOMMUTEDISTANCE,
        T.$60 AS AUTOHASABS,
        T.$61 AS AUTOHASAIRBAGS,
        T.$62 AS AUTOINSBODILYINJURYCOVERAGE,
        T.$63 AS AUTOINSCOLLISIONDEDUCTIBLE,
        T.$64 AS AUTOINSCOMPREHENSIVEDEDUCTIBLE,
        T.$65 AS AUTOINSCOVERAGETYPE,
        T.$66 AS AUTOINSCOVERAGETYPEREQUESTED,
        T.$67 AS AUTOINSPROPERTYDAMAGECOVERAGE,
        T.$68 AS AUTOMAKE,
        T.$69 AS AUTOPRIMARYUSE,
        T.$70 AS AUTOYEAR,
        T.$71 AS CC_AMEX_PREM,
        T.$72 AS CC_AMEX_REG,
        T.$73 AS CC_BANK_CD_IN_HH,
        T.$74 AS CC_DISC_PREM,
        T.$75 AS CC_DISC_REG,
        T.$76 AS CC_GAS_PREM,
        T.$77 AS CC_GAS_REG,
        T.$78 AS CC_HLDR_BANK,
        T.$79 AS CC_HLDR_GAS,
        T.$80 AS CC_HLDR_PREM,
        T.$81 AS CC_HLDR_TE,
        T.$82 AS CC_HLDR_UNK,
        T.$83 AS CC_HLDR_UPS_DEPT,
        T.$84 AS CC_MC_PREM,
        T.$85 AS CC_MC_REG,
        T.$86 AS CC_NEW_ISSUE,
        T.$87 AS CC_USER,
        T.$88 AS CC_VISA_PREM,
        T.$89 AS CC_VISA_REG,
        T.$90 AS CENSUS_BLOCK_GROUP,
        T.$91 AS CENSUS_TRACT,
        T.$92 AS CITY,
        T.$93 AS CREDIT_LINES,
        T.$94 AS CREDIT_RANGE_NEW,
        T.$95 AS CREDIT_RATING,
        T.$96 AS DOB_DAY,
        T.$97 AS DOB_MON,
        T.$98 AS DOB_YR,
        T.$99 AS DOMAIN,
        T.$100 AS DONR_ANIMAL,
        T.$101 AS DONR_ARTS,
        T.$102 AS DONR_CHARITABLE,
        T.$103 AS DONR_COMM_CHAR,
        T.$104 AS DONR_ENVIRON,
        T.$105 AS DONR_HEALTH,
        T.$106 AS DONR_INTL_AID,
        T.$107 AS DONR_KIDS,
        T.$108 AS DONR_MAIL_ORD,
        T.$109 AS DONR_OTH,
        T.$110 AS DONR_POL,
        T.$111 AS DONR_POL_CONS,
        T.$112 AS DONR_POL_LIB,
        T.$113 AS DONR_RELIG,
        T.$114 AS DONR_VETS,
        T.$115 AS DONR_WILDLIFE,
        T.$116 AS DRIVERSLICENSEEVERREVOKED,
        T.$117 AS DRIVERSLICENSESTATE,
        T.$118 AS DWELL_TYPE,
        T.$119 AS EDUCATION_LEVEL,
        T.$120 AS ETHNIC_ASSIM,
        T.$121 AS ETHNIC_CONF,
        T.$122 AS ETHNIC_GRP,
        T.$123 AS ETHNIC_HISP_CNTRY,
        T.$124 AS ETHNIC_LANG,
        T.$125 AS ETHNIC_RELIG,
        CAST(T.$126 AS NUMBER) AS EXACT_AGE,
        T.$127 AS FIPS_STATE_CODE,
        T.$128 AS GENERATIONS,
        T.$129 AS GENL_PP_HOME_VALUE,
        T.$130 AS HH_INCOME,
        T.$131 AS HH_MARITAL_STATUS,
        T.$132 AS INVEST_ACT,
        T.$133 AS INVEST_FOREIGN,
        T.$134 AS INVEST_MONEY_SEEKR,
        T.$135 AS INVEST_PERS,
        T.$136 AS INVEST_READ_FIN_NEWS,
        T.$137 AS INVEST_RL_EST,
        T.$138 AS INVEST_STOCKS,
        T.$139 AS KIDS_F_0_2,
        T.$140 AS KIDS_F_11_15,
        T.$141 AS KIDS_F_16_17,
        T.$142 AS KIDS_F_3_5,
        T.$143 AS KIDS_F_6_10,
        T.$144 AS KIDS_M_0_2,
        T.$145 AS KIDS_M_11_15,
        T.$146 AS KIDS_M_16_17,
        T.$147 AS KIDS_M_3_5,
        T.$148 AS KIDS_M_6_10,
        T.$149 AS KIDS_U_0_2,
        T.$150 AS KIDS_U_11_15,
        T.$151 AS KIDS_U_16_17,
        T.$152 AS KIDS_U_3_5,
        T.$153 AS KIDS_U_6_10,
        CAST(T.$154 AS NUMBER) AS LENGTH_OF_RESIDENCE,
        T.$155 AS MAGS,
        TO_DATE(T.$156) AS MOTORCYCLE_DATE,
        T.$157 AS MOTORCYCLE_MODEL,
        T.$158 AS MOTORCYCLE_VIN,
        T.$159 AS MR_LENDR_CD,
        T.$160 AS MR_LOAN_TYP,
        T.$161 AS MR2_AMT,
        T.$162 AS MR2_LENDR,
        T.$163 AS MR2_LENDER_CD,
        T.$164 AS MR2_LOAN_TYP,
        T.$165 AS MR2_RATE_TYP,
        T.$166 AS NAME_SUFFIX,
        T.$167 AS NUM_ADULTS,
        T.$168 AS NUM_KIDS,
        T.$169 AS OCC_AFRIC_AMER_PROF,
        T.$170 AS OCC_BUSN_OWNR,
        T.$171 AS OCC_HOME_OFF,
        T.$172 AS OCC_SOHO_IND,
        T.$173 AS OCC_WORKING_WMN,
        TO_TIMESTAMP(T.$174) AS OPTIN_DATE,
        T.$175 AS P2_AMT,
        T.$176 AS P2_LOAN_TYP,
        T.$177 AS P2_RATE_TYP,
        T.$178 AS PARTY_AFFILIATION,
        T.$179 AS PAYDAY_EMPLOYER_NAME,
        T.$180 AS PAYDAY_EMPLOYMENT_STATUS,
        T.$181 AS PAYDAY_FLAG,
        T.$182 AS PAYDAY_LOAN_REQUESTED_AMT,
        T.$183 AS PAYDAY_MILITARY_FLAG,
        T.$184 AS PAYDAY_OCCUPATION,
        T.$185 PRES_KIDS,
        T.$186 AS PROP_AC,
        T.$187 AS PROP_FUEL,
        T.$188 AS PROP_POOL,
        T.$189 AS PROP_SEWER,
        T.$190 AS PROP_TYPE,
        T.$191 AS PROP_WATER,
        T.$192 AS SINGLE_PARENT,
        T.$193 AS SR_ADULT_IN_HH,
        T.$194 AS STATE,
        T.$195 AS URL,
        T.$196 AS VET_IN_HH,
        T.$197 AS WALK_SEQUENCE_CODE,
        T.$198 AS YOUNG_ADULT_IN_HH,
        T.$199 AS ZIP,
        T.$200 AS ZIP4,
        T.$201 AS PERSONAL_PHONE_DNC_FLAG,
        T.$202 AS MOBILE_PHONE_DNC_FLAG,
        T.$203 AS UPID
        FROM @FOUR_EYES.PUBLIC.AUDIENCELAB_BACKUP_STAGE/consumer_b2c_full/ AS T
    );





SELECT * FROM AUDIENCELAB_INTERNAL_PROD.PUBLIC.CONSUMER_B2C_FULL LIMIT 10000;








-- Fill AUDIENCELAB_INTERNAL_PROD.PUBLIC.B2B_EXPORT_TROVO with data:
COPY INTO AUDIENCELAB_INTERNAL_PROD.PUBLIC.B2B_EXPORT_TROVO
    FROM
    (
    SELECT 
    CAST(T.$1 AS NUMBER) AS ID,
    T.$2 AS FIRST_NAME,
    T.$3 AS LAST_NAME,
    T.$4 AS BUSINESS_EMAIL,
    T.$5 AS SHA256_BUSINESS_EMAIL,
    T.$6 AS PROGRAMMATIC_BUSINESS_EMAILS,
    T.$7 AS PERSONAL_EMAIL,
    T.$8 AS SHA256_PERSONAL_EMAIL,
    T.$9 AS JOB_TITLE,
    T.$10 AS SENIORITY_LEVEL,
    T.$11 AS DEPARTMENT,
    T.$12 AS MOBILE_PHONE,
    T.$13 AS DIRECT_NUMBER,
    T.$14 AS LINKEDIN_URL,
    T.$15 AS PERSONAL_ADDRESS,
    T.$16 AS PERSONAL_ADDRESS_2,
    T.$17 AS PERSONAL_CITY,
    T.$18 AS PERSONAL_STATE,
    T.$19 AS PERSONAL_ZIP,
    T.$20 AS PERSONAL_ZIP4,
    T.$21 AS PROFESSIONAL_ADDRESS,
    T.$22 AS PROFESSIONAL_ADDRESS_2,
    T.$23 AS PROFESSIONAL_CITY,
    T.$24 AS PROFESSIONAL_STATE,
    T.$25 AS PROFESSIONAL_ZIP,
    T.$26 AS PROFESSIONAL_ZIP4,
    T.$27 AS COMPANY_NAME,
    T.$28 AS COMPANY_DOMAIN,
    T.$29 AS COMPANY_PHONE,
    T.$30 AS PRIMARY_INDUSTRY,
    T.$31 AS COMPANY_SIC,
    T.$32 AS COMPANY_NAICS,
    T.$33 AS COMPANY_ADDRESS,
    T.$34 AS COMPANY_ADDRESS_2,
    T.$35 AS COMPANY_CITY,
    T.$36 AS COMPANY_STATE,
    T.$37 AS COMPANY_ZIP,
    T.$38 AS COMPANY_ZIP4,
    T.$39 AS COMPANY_LINKEDIN_URL,
    T.$40 AS COMPANY_REVENUE,
    T.$41 AS COMPANY_EMPLOYEE_COUNT,
    T.$42 AS BUSINESS_EMAIL_VALIDATION_STATUS,
    TO_TIMESTAMP(T.$43) AS BUSINESS_EMAIL_LAST_SEEN,
    TO_TIMESTAMP(T.$44) AS COMPANY_LAST_UPDATED,
    TO_TIMESTAMP(T.$45) AS JOB_TITLE_LAST_UPDATED,
    TO_TIMESTAMP(T.$46) AS LAST_UPDATED
    FROM @FOUR_EYES.PUBLIC.AUDIENCELAB_BACKUP_STAGE/b2b_export_trovo AS T;
    );


-- Fill AUDIENCELAB_INTERNAL_PROD.PUBLIC.ST_CONSUMER with data:
    COPY INTO AUDIENCELAB_INTERNAL_PROD.PUBLIC.ST_CONSUMER 
    FROM (
        SELECT
        TO_DATE(T.$1) AS UTC_DATE,
        T.$2 AS KEYWORD,
        T.$3 AS INDIVIDUALID
        FROM @FOUR_EYES.PUBLIC.AUDIENCELAB_BACKUP_STAGE/st_consumer AS T
    );


-- Fill AUDIENCELAB_INTERNAL_PROD.PUBLIC.PREMADE_TAXONOMY with data:
COPY INTO AUDIENCELAB_INTERNAL_PROD.PUBLIC.PREMADE_TAXONOMY
FROM (
    SELECT 
    T.$1 AS ID,
    T.$2 AS NAME
    FROM @FOUR_EYES.PUBLIC.AUDIENCELAB_BACKUP_STAGE/premade_taxonomy AS T
);


-- Fill FOUR_EYES.PUBLIC.SHA_TO_UPS with data:
  --  COPY INTO FOUR_EYES.PUBLIC.SHA_TO_UPS
--    FROM (
 --       SELECT 
  --      T.$1 AS SHA256_LC_HEM,
  --      T.$2 AS UP_IDS
 --       FROM @FOUR_EYES.PUBLIC.AUDIENCELAB_BACKUP_STAGE/sha_to_ups AS T
 --   );


    COPY INTO FOUR_EYES.PUBLIC.SHA_TO_UPS
    FROM (
    SELECT   -- parse data from aws s3 location.
    T.$1:"SHA256_LC_HEM"::string AS "SHA256_LC_HEM",
    T.$1:"UP_IDS" AS "UP_IDS"
    FROM @FOUR_EYES.PUBLIC.FOUR_EYES_STAGE_JSON/dt=20240213/
    (FILE_FORMAT => FOUR_EYES.PUBLIC.FOUR_EYES_JSON_FORMAT) T
      );


    SELECT COUNT(*) FROM FOUR_EYES.PUBLIC.SHA_TO_UPS;








    

    