
CREATE OR REPLACE TABLE AUDIENCELAB_INTERNAL_PROD.PUBLIC.TROVO_FEED_RESOLVED (
    TROVO_ID VARCHAR(16777216),
	PARTNER_ID VARCHAR(16777216),
	PARTNER_UID VARCHAR(16777216),
	SHA256_LOWER_CASE VARCHAR(16777216),
	IP VARCHAR(16777216),
	EVENT_DATE TIMESTAMP_NTZ(9),
	INGESTION_TIMESTAMP TIMESTAMP_NTZ(9)
);

// Copy TROVO_FEED_RESOLVED data, from S3, into TROVO_FEED_RESOLVED table:
COPY INTO AUDIENCELAB_INTERNAL_PROD.PUBLIC.TROVO_FEED_RESOLVED
FROM (
SELECT 
T.$1 AS TROVO_ID,
T.$2 AS PARTNER_ID,
T.$3 AS PARTNER_UID,
T.$4 AS SHA256_LOWER_CASE,
T.$5 AS IP,
TO_TIMESTAMP(T.$6) AS EVENT_DATE,
TO_TIMESTAMP(T.$7) AS INGESTION_TIMESTAMP
FROM @FOUR_EYES.PUBLIC.AUDIENCELAB_BACKUP_STAGE/trovo_feed_resolved/ AS T
);






SELECT * FROM AUDIENCELAB_INTERNAL_PROD.PUBLIC.TROVO_FEED_RESOLVED LIMIT 1000;
