
CREATE TABLE AUDIENCELAB_INTERNAL_PROD.PUBLIC.KEYWORD_PLANNER (
    UTC_DATE DATE,
	KEYWORD VARCHAR(16777216),
	COUNT NUMBER
);AUDIENCELAB_INTERNAL_PROD;


COPY INTO AUDIENCELAB_INTERNAL_PROD.PUBLIC.KEYWORD_PLANNER
FROM (
SELECT 
TO_DATE(T.$1) AS UTC_DATE,
T.$2 AS KEYWORD,
CAST(T.$3 AS NUMBER) AS COUNT
FROM @FOUR_EYES.PUBLIC.AUDIENCELAB_BACKUP_STAGE/keyword_planner/ AS T
);


SELECT COUNT(*) FROM AUDIENCELAB_INTERNAL_PROD.PUBLIC.KEYWORD_PLANNER;


SELECT * FROM AUDIENCELAB_INTERNAL_PROD.PUBLIC.KEYWORD_PLANNER LIMIT 1000;
