CREATE OR REPLACE FILE FORMAT FOUR_EYES.PUBLIC.FOUR_EYES_CSV_FORMAT
    TYPE=CSV,
    FIELD_DELIMITER=',',
    SKIP_HEADER=1,
    NULL_IF=('NULL', 'null')
    COMPRESSION=gzip;



CREATE OR REPLACE FILE FORMAT FOUR_EYES.PUBLIC.FOUR_EYES_CSV_FORMAT_2
    TYPE=CSV,
    FIELD_DELIMITER=',',
    SKIP_HEADER=0,
    NULL_IF=('NULL', 'null')
    COMPRESSION=gzip;


    CREATE OR REPLACE FILE FORMAT TROVO.PUBLIC.UNIVERSAL_PERSON_FILE_FORMAT_2
	SKIP_HEADER = 0
	FIELD_OPTIONALLY_ENCLOSED_BY = '\"'
	NULL_IF = ('', 'null', 'NULL')
	COMPRESSION = GZIP
;



CREATE OR REPLACE FILE FORMAT FOUR_EYES.PUBLIC.FOUR_EYES_JSON_FORMAT
    TYPE=JSON,
    COMPRESSION=gzip;




CREATE OR REPLACE FILE FORMAT FOUR_EYES.PUBLIC.FOUR_EYES_PARQUET_FORMAT
  TYPE = 'PARQUET'
  COMPRESSION = 'SNAPPY';